services:
  db:
    image: mariadb:latest
    container_name: keto_database
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - db_data_keto:/var/lib/mysql

volumes:
  db_data_keto: